spring:
  rabbitmq:
    password: guest
    username: guest
    addresses: 127.0.0.1
    port: 5672  # 注意，这里是5672，不是访问界面用的15672，这个是默认值
    template:
      exchange: testMessageInput
  cloud:
    stream:
      rabbit:
        binder:
          admin-addresses:
          compression-level:
          connection-name-prefix:
          nodes: